environments:
  development:
    subscription-id: "12345678-1234-1234-1234-123456789012"
    resource-group: "test-rg"
    location: "East US"
    storage-account: "teststorage"
    key-vault: "test-kv"

  staging:
    subscription-id: "87654321-4321-4321-4321-210987654321"
    resource-group: "staging-rg"
    location: "West US 2"
    storage-account: "stagingstorage"
    key-vault: "staging-kv"
