name: Pull Request Checks

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Require scope to be action name or 'shared' or 'all'
          scopes: |
            hello-world
            hello-user
            hello-time
            shared
            all
          
          # Types that map to version bumps
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
            build
            ci
          
          # Require scope for better tracking
          requireScope: true
          
          # Allow breaking change indicator
          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}" didn't match the configured pattern.
            Please ensure that the subject starts with an uppercase character.
